# Example TFE Configuration
# Replace these values with your actual TFE details

tfe_server: app.terraform.io
organization: your-organization-name
token: your-api-token-here
workspace_id: ws-ABC123456789
run_id: run-XYZ987654321

# Optional settings
verify_ssl: true
timeout: 30
retry_attempts: 3